### ISSUE TITLE
代码已经写不到本地了

### ISSUE THREAD

**Issue by Yueqi-19** [JiayangWu/LeetCodeCN-Submissions-Crawler#17]
你好，您的爬虫代码我觉得对我很有用。我用了两周了，23号还能正常使用，到了25号就失效了，爬不出来了。
今早我已经试了很多遍，发现今天提交的AC代码已经写不到本地了，只会出现 很多个”Java" 和“ was not accepted".
我今天试着做了leetcode反转链表的题，在leetcode上提交通过了，然后我准备爬到我的电脑本地，出现了以下的情况。我想问下是题目列表更新了吗？我仔细看了题目列表，并没有变化。还是leetcode的爬虫逻辑方式改变了？还需要优化维护吗？十分感谢您的解答！

<a href="https://sm.ms/image/5ys46pq8enfEDZ3" target="_blank"><img src="https://i.loli.net/2020/07/27/5ys46pq8enfEDZ3.png" /></a>
```python
C:\Users\liyue\LeetCodeCN-Submissions-Crawler>C:/Users/liyue/Anaconda3/Scripts/activate

(base) C:\Users\liyue\LeetCodeCN-Submissions-Crawler>conda activate base

(base) C:\Users\liyue\LeetCodeCN-Submissions-Crawler>C:/Users/liyue/Anaconda3/python.exe c:/Users/liyue/LeetCodeCN-Submissions-Crawler/main.py
login
Login successfully!
start scrapping
Now for page: 0
'Java'
反转链表 was not Accepted, continue for the next submission
反转链表 was not Accepted, continue for the next submission
'Java'
'Java'
'Java'
'Java'
两数相加 was not Accepted, continue for the next submission
'Java'
end scrapping
~~~~~~~~~~~~~git add . finished! ~~~~~~~~
On branch master
Your branch is up to date with 'origin/master'.
```

**Comment by JiayangWu** [comment]
你好，感谢反馈！
目前已经定位到问题原因，之前的提交代码可以明文获取的，现在LCCN提供的是提交代码对应的一个url，所以爬取内容会失败。
修复的方法是从类似 https://leetcode-cn.com/submissions/detail/91765349/ 的链接里爬取代码。
我试着修复了一下，目前没啥进展。

**Comment by Yueqi-19** [comment]
好的明白了 谢谢您 我也试着修复下 如果修复好就pull requests
Thanks a lot

Celia_Wu <notifications@github.com> 于2020年7月26日周日 下午3:39写道：

**Comment by JiayangWu** [comment]
你好，已经修复完成，可以试一下了。

**Comment by Yueqi-19** [comment]
谢谢！我现在去调试下

Celia_Wu <notifications@github.com>于2020年7月27日 周一下午8:28写道：

**Comment by Yueqi-19** [comment]
```python
import unicodedata
import sys, os, time
from ProblemList import GetProblemId
import requests, json
from bs4 import BeautifulSoup
import json
import re
from retrying import retry #刚才我在我电脑这边把retry 改成retrying, 然后更新了自己的path
```
就正常运行了 感谢楼主！

**Comment by JiayangWu** [comment]
不客气，感谢反馈！
