### ISSUE TITLE
expected string or bytes-like object  Unknwon bug happened

### ISSUE THREAD

**Issue by KatePang13** [JiayangWu/LeetCodeCN-Submissions-Crawler#19]
start scrapping
Now for page: 0
expected string or bytes-like object  Unknwon bug happened, please raise issue with your log to the writer.

哈, 今天爬不了了...

**Comment by JiayangWu** [comment]
修好了，你再试试 :)

**Comment by JiayangWu** [comment]
14天未收到回复，关闭此issue。
