### ISSUE TITLE
Login failed! Wait till next round!

### ISSUE THREAD

**Issue by LenmonLin** [JiayangWu/LeetCodeCN-Submissions-Crawler#2]
按照大佬的安装指引，运行时错误，无法登陆

**Comment by LenmonLin** [comment]
密码和用户名都修改为自己的了

**Comment by LenmonLin** [comment]
@JiayangWu

**Comment by JiayangWu** [comment]
你好，把login函数改成下面的试一下
`def login(email, password): # 本函数copy自https://gist.github.com/fyears/487fc702ba814f0da367a17a2379e8ba，感谢@fyears
    client = requests.session()
    client.encoding = "utf-8"

    while True:
        try:
            client.get(sign_in_url, verify=False)
            login_data = {'login': email, 
                'password': password
            }
            result = client.post(sign_in_url, data=login_data, headers=dict(Referer=sign_in_url))
            if result.ok:
                print ("Login successfully!")
                break
        except:
            print ("Login failed! Wait till next round!")
            time.sleep(sleep_time)

    return client`

**Comment by JiayangWu** [comment]
问题已经解决，处理方式为：
1. 修改登录模块，2019年8月8日可以登陆成功。
2. 提醒用户本项目是爬取个人代码，而非官方代码。
