### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by cleiveliu** [JiayangWu/LeetCodeCN-Submissions-Crawler#3]
https://github.com/JiayangWu/LeetCodeCN-Submissions-Crawler/blob/a564e2499de2b326a809feafd60d018af4006ef7/ProblemListGenerator.py#L3

'1.txt'是gbk编码的,在默认编码不为gbk的系统上打开出错，

**Comment by JiayangWu** [comment]
你好，我把这行改成以下就可以用了，你看看现在行了不
`with open("1.txt", "r", encoding='UTF-8') as f:`
