### ISSUE TITLE
貌似不行了，力扣中国改了登录方式了，跑步起来，兄弟能修改下吗

### ISSUE THREAD

**Issue by xww** [JiayangWu/LeetCodeCN-Submissions-Crawler#4]
貌似不行了，力扣中国改了登录方式了，跑不起来，兄弟能修改下吗

**Comment by cleiveliu** [comment]
老哥，登录方式没有变的，稍微改一下可以用的

**Comment by cleiveliu** [comment]
老哥，我昨天用的时候改了一下，能跑，改得挺粗糙的，所以也就不pr了，直接打包上传
https://github.com/cleiveliu/collections/tree/master/collections/tem
main.py稍微改了一下然后配置一下就可以用了

**Comment by xww** [comment]
> 老哥，我昨天用的时候改了一下，能跑，改得挺粗糙的，所以也就不pr了，直接打包上传
> https://github.com/cleiveliu/collections/tree/master/collections/tem
> main.py稍微改了一下然后配置一下就可以用了

csrftoken = client.cookies['csrftoken'] 51行这句代码，娶不到csfrtoken啊，leetcode.com可以取到，leetcode-cn.com就没有，你是咋login上去的？

**Comment by cleiveliu** [comment]
我写好我的账号密码后，这个脚本是可以登陆的，我不知道，它是登陆后才设置的csrftoken, 你的可以登陆吗

**Comment by JiayangWu** [comment]
更新了一下登录方式，我可以跑起来了，你看看现在可以用了不

**Comment by JiayangWu** [comment]
两周内无人回应，特此关闭。
