### ISSUE TITLE
请问最近会有登陆的问题吗？

### ISSUE THREAD

**Issue by ihanwen99** [JiayangWu/LeetCodeCN-Submissions-Crawler#44]
RT

**Comment by JiayangWu** [comment]
是的，一直返回错误代码500。 详见 Issue #37

**Comment by ihanwen99** [comment]
感谢回复。经过实验我发现使用 cookie 登陆可以稳定建立连接。使用如下的header即可。

```python
headers = {'User-Agent': user_agent, 'Referer': sign_in_url, 'Cookie': COOKIES, 'Connection': 'keep-alive'}
```

我在我的 crawler 里面实现了这个功能 [LeetCode-CN-Crawler](https://github.com/david990917/LeetCode-CN-Crawler/blob/master/leetcode-cn-crawler.py) :)

**Comment by ihanwen99** [comment]
如果可以，我可以提交一个PR尝试实现这个功能。希望成为 contributor :)

**Comment by JiayangWu** [comment]
> 如果可以，我可以提交一个PR尝试实现这个功能。希望成为 contributor :)

欢迎欢迎！

**Comment by ihanwen99** [comment]
The cookie interface is implemented in https://github.com/JiayangWu/LeetCodeCN-Submissions-Crawler/pull/45 :)

**Comment by JiayangWu** [comment]
PR已经merge，感谢贡献！
