### ISSUE TITLE
关于login的方法

### ISSUE THREAD

**Issue by Zhenxuyang** [JiayangWu/LeetCodeCN-Submissions-Crawler#7]
login函数出处的链接已经失效了,能解释下为什么post请求要这么传参

"""
client.get(sign_in_url, verify=False)

            login_data = {'login': email, 
                'password': password
            }
            
            result = client.post(sign_in_url, data=login_data, headers=dict(Referer=sign_in_url))
"""
在页面抓包，好像不是这么请求的

**Comment by JiayangWu** [comment]
你好，这我真的不知道，最初版本的函数是直接copy出处的，后来又因为网站登录方式改动我自己小改了一下。

原始代码为：
def login(email, password): # 本函数copy自https://gist.github.com/fyears/487fc702ba814f0da367a17a2379e8ba，感谢@fyears
     client = requests.session()
     client.encoding = "utf-8"

     while True:
         try:
             client.get(sign_in_url, verify=False)
             csrftoken = client.cookies['csrftoken']
             login_data = {'login': email, 
                 'password': password,
                 'csrfmiddlewaretoken': csrftoken
             }
             result = client.post(sign_in_url, data=login_data, headers=dict(Referer=sign_in_url))

             if result.ok:
                 print ("Login successfully!")
                 break
         except:
             print ("Login failed! Wait till next round!")
             time.sleep(sleep_time)

     return client

**Comment by Zhenxuyang** [comment]
好的，多谢

**Comment by JiayangWu** [comment]
正常关闭。
