### ISSUE TITLE
fatal: 不是一个 git 仓库（或者任何父目录）：.git

### ISSUE THREAD

**Issue by yydcyy01** [JiayangWu/LeetCodeCN-Submissions-Crawler#9]
如题, 这是什么意思. google 了下说 git init 即可. 
试了不行. 可为什么会和 git 有关么? 没解决, 不理解

**Comment by NKUlpj** [comment]
就是本地文件夹是个仓库！可以在github上新建一个仓库，然后本地仓库提交一次就行，比如提交一个readme就可以了！这个项目将leetcode 的题解爬取到本地，然后调用push提交到远程仓库的！所以本地文件夹要和github仓库关联上

**Comment by JiayangWu** [comment]
本仓库代码是包含了一键上传github的功能的，所以必须首先有本地git记录，也就是得 git init。
如果你只需要将代码爬到本地，则关闭main.py文件里的git_push()这个函数即可。

**Comment by JiayangWu** [comment]
超过14天没有得到回复，关闭此issue。
